

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."colour" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."colour" OWNER TO "postgres";


ALTER TABLE "public"."colour" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."colour_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."listing" (
    "id" bigint NOT NULL,
    "price" bigint NOT NULL,
    "description" "text",
    "listed_on" timestamp with time zone NOT NULL,
    "sold_on" timestamp with time zone,
    "is_active" boolean DEFAULT true NOT NULL,
    "vehicle_id" bigint NOT NULL,
    "patron_id" bigint NOT NULL
);


ALTER TABLE "public"."listing" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."make" (
    "id" bigint NOT NULL,
    "brand_name" "text" NOT NULL
);


ALTER TABLE "public"."make" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."vehicle" (
    "id" bigint NOT NULL,
    "make_id" bigint NOT NULL,
    "model_id" bigint NOT NULL,
    "year_id" bigint NOT NULL,
    "colour_id" bigint NOT NULL,
    "drivetrain_id" bigint NOT NULL
);


ALTER TABLE "public"."vehicle" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."count_of_vehicles_by_brand" AS
 SELECT "mk"."brand_name" AS "brand",
    "count"("l"."id") AS "vehicles_available"
   FROM (("public"."listing" "l"
     JOIN "public"."vehicle" "v" ON (("l"."vehicle_id" = "v"."id")))
     JOIN "public"."make" "mk" ON (("v"."make_id" = "mk"."id")))
  WHERE ("l"."is_active" = true)
  GROUP BY "mk"."brand_name";


ALTER VIEW "public"."count_of_vehicles_by_brand" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."drivetrain" (
    "id" bigint NOT NULL,
    "acronym" "text" NOT NULL,
    "description" "text" NOT NULL
);


ALTER TABLE "public"."drivetrain" OWNER TO "postgres";


ALTER TABLE "public"."drivetrain" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."drivetrain_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."listing" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."model" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "make_id" bigint NOT NULL
);


ALTER TABLE "public"."model" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."year" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."year" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."listings_with_details" WITH ("security_invoker"='on') AS
 SELECT "l"."id",
    "l"."price",
    "l"."description",
    "l"."listed_on",
    "mk"."brand_name" AS "brand",
    "mdl"."name" AS "model",
    "y"."name" AS "year",
    "c"."name" AS "colour",
    "d"."description" AS "drivetrain"
   FROM (((((("public"."listing" "l"
     JOIN "public"."vehicle" "v" ON (("l"."vehicle_id" = "v"."id")))
     JOIN "public"."make" "mk" ON (("v"."make_id" = "mk"."id")))
     JOIN "public"."model" "mdl" ON (("v"."model_id" = "mdl"."id")))
     JOIN "public"."year" "y" ON (("v"."year_id" = "y"."id")))
     JOIN "public"."colour" "c" ON (("v"."colour_id" = "c"."id")))
     JOIN "public"."drivetrain" "d" ON (("v"."drivetrain_id" = "d"."id")))
  WHERE ("l"."is_active" = true);


ALTER VIEW "public"."listings_with_details" OWNER TO "postgres";


ALTER TABLE "public"."make" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."make_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."model" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."model_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."patron" (
    "id" bigint NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email_address" "text" NOT NULL,
    "phone_number" "text"
);


ALTER TABLE "public"."patron" OWNER TO "postgres";


ALTER TABLE "public"."patron" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."patron_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saved" (
    "id" bigint NOT NULL,
    "saved_on" timestamp with time zone DEFAULT "now"() NOT NULL,
    "patron_id" bigint NOT NULL,
    "listing_id" bigint NOT NULL
);


ALTER TABLE "public"."saved" OWNER TO "postgres";


ALTER TABLE "public"."saved" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."saved_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."saved_listings" WITH ("security_invoker"='on') AS
 SELECT "lwd"."id",
    "s"."saved_on",
    "s"."patron_id",
    "lwd"."price",
    "lwd"."description",
    "lwd"."listed_on",
    "lwd"."brand",
    "lwd"."model",
    "lwd"."year",
    "lwd"."colour",
    "lwd"."drivetrain"
   FROM ("public"."saved" "s"
     JOIN "public"."listings_with_details" "lwd" ON (("s"."listing_id" = "lwd"."id")));


ALTER VIEW "public"."saved_listings" OWNER TO "postgres";


ALTER TABLE "public"."vehicle" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."vehicle_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."year" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."year_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."colour"
    ADD CONSTRAINT "colour_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."drivetrain"
    ADD CONSTRAINT "drivetrain_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listing"
    ADD CONSTRAINT "listing_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."make"
    ADD CONSTRAINT "make_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."model"
    ADD CONSTRAINT "model_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."patron"
    ADD CONSTRAINT "patron_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saved"
    ADD CONSTRAINT "saved_patron_id_listing_id_key" UNIQUE ("patron_id", "listing_id");



ALTER TABLE ONLY "public"."saved"
    ADD CONSTRAINT "saved_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vehicle"
    ADD CONSTRAINT "vehicle_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."year"
    ADD CONSTRAINT "year_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_listing_is_active" ON "public"."listing" USING "btree" ("is_active");



CREATE INDEX "idx_listing_patron_id" ON "public"."listing" USING "btree" ("patron_id");



CREATE INDEX "idx_listing_vehicle_id" ON "public"."listing" USING "btree" ("vehicle_id");



CREATE INDEX "idx_saved_listing_id" ON "public"."saved" USING "btree" ("listing_id");



CREATE INDEX "idx_saved_patron_id" ON "public"."saved" USING "btree" ("patron_id");



CREATE INDEX "idx_vehicle_make_id" ON "public"."vehicle" USING "btree" ("make_id");



CREATE INDEX "idx_vehicle_model_id" ON "public"."vehicle" USING "btree" ("model_id");



ALTER TABLE ONLY "public"."listing"
    ADD CONSTRAINT "listing_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "public"."patron"("id");



ALTER TABLE ONLY "public"."listing"
    ADD CONSTRAINT "listing_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicle"("id");



ALTER TABLE ONLY "public"."model"
    ADD CONSTRAINT "model_make_id_fkey" FOREIGN KEY ("make_id") REFERENCES "public"."make"("id");



ALTER TABLE ONLY "public"."saved"
    ADD CONSTRAINT "saved_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listing"("id");



ALTER TABLE ONLY "public"."saved"
    ADD CONSTRAINT "saved_patron_id_fkey" FOREIGN KEY ("patron_id") REFERENCES "public"."patron"("id");



ALTER TABLE ONLY "public"."vehicle"
    ADD CONSTRAINT "vehicle_colour_id_fkey" FOREIGN KEY ("colour_id") REFERENCES "public"."colour"("id");



ALTER TABLE ONLY "public"."vehicle"
    ADD CONSTRAINT "vehicle_drivetrain_id_fkey" FOREIGN KEY ("drivetrain_id") REFERENCES "public"."drivetrain"("id");



ALTER TABLE ONLY "public"."vehicle"
    ADD CONSTRAINT "vehicle_make_id_fkey" FOREIGN KEY ("make_id") REFERENCES "public"."make"("id");



ALTER TABLE ONLY "public"."vehicle"
    ADD CONSTRAINT "vehicle_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "public"."model"("id");



ALTER TABLE ONLY "public"."vehicle"
    ADD CONSTRAINT "vehicle_year_id_fkey" FOREIGN KEY ("year_id") REFERENCES "public"."year"("id");



CREATE POLICY "Enable all operations for authenticated users" ON "public"."saved" TO "authenticated" USING (true);



CREATE POLICY "Enable full access for authenticated users" ON "public"."patron" TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."colour" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."drivetrain" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."listing" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."make" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."model" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."vehicle" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."year" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."colour" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."drivetrain" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listing" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."make" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."model" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."patron" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."saved" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vehicle" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."year" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."listing";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."saved";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."vehicle";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."colour" TO "anon";
GRANT ALL ON TABLE "public"."colour" TO "authenticated";
GRANT ALL ON TABLE "public"."colour" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colour_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."colour_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colour_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."listing" TO "anon";
GRANT ALL ON TABLE "public"."listing" TO "authenticated";
GRANT ALL ON TABLE "public"."listing" TO "service_role";



GRANT ALL ON TABLE "public"."make" TO "anon";
GRANT ALL ON TABLE "public"."make" TO "authenticated";
GRANT ALL ON TABLE "public"."make" TO "service_role";



GRANT ALL ON TABLE "public"."vehicle" TO "anon";
GRANT ALL ON TABLE "public"."vehicle" TO "authenticated";
GRANT ALL ON TABLE "public"."vehicle" TO "service_role";



GRANT ALL ON TABLE "public"."count_of_vehicles_by_brand" TO "anon";
GRANT ALL ON TABLE "public"."count_of_vehicles_by_brand" TO "authenticated";
GRANT ALL ON TABLE "public"."count_of_vehicles_by_brand" TO "service_role";



GRANT ALL ON TABLE "public"."drivetrain" TO "anon";
GRANT ALL ON TABLE "public"."drivetrain" TO "authenticated";
GRANT ALL ON TABLE "public"."drivetrain" TO "service_role";



GRANT ALL ON SEQUENCE "public"."drivetrain_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."drivetrain_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."drivetrain_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."listing_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."listing_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."listing_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."model" TO "anon";
GRANT ALL ON TABLE "public"."model" TO "authenticated";
GRANT ALL ON TABLE "public"."model" TO "service_role";



GRANT ALL ON TABLE "public"."year" TO "anon";
GRANT ALL ON TABLE "public"."year" TO "authenticated";
GRANT ALL ON TABLE "public"."year" TO "service_role";



GRANT ALL ON TABLE "public"."listings_with_details" TO "anon";
GRANT ALL ON TABLE "public"."listings_with_details" TO "authenticated";
GRANT ALL ON TABLE "public"."listings_with_details" TO "service_role";



GRANT ALL ON SEQUENCE "public"."make_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."make_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."make_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."model_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."model_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."model_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."patron" TO "anon";
GRANT ALL ON TABLE "public"."patron" TO "authenticated";
GRANT ALL ON TABLE "public"."patron" TO "service_role";



GRANT ALL ON SEQUENCE "public"."patron_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."patron_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."patron_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saved" TO "anon";
GRANT ALL ON TABLE "public"."saved" TO "authenticated";
GRANT ALL ON TABLE "public"."saved" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saved_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saved_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saved_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saved_listings" TO "anon";
GRANT ALL ON TABLE "public"."saved_listings" TO "authenticated";
GRANT ALL ON TABLE "public"."saved_listings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vehicle_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vehicle_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vehicle_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."year_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."year_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."year_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























